assetic:
  java: /usr/bin/java
  filters:
    cssembed:
      jar: %kernel.root_dir%/../bin/java/cssembed-0.4.5.jar
    yui_js:
      jar: %kernel.root_dir%/../bin/java/yuicompressor.jar
    lessphp:
      file: %kernel.root_dir%/../vendor/oyejorge/less.php/lessc.inc.php
      apply_to: "\.less$"
  assets:
    jquery_js:
        inputs:
            - '%kernel.root_dir%/../app/Resources/public/js/jquery/jquery.js'
        filters: [?yui_js]
    bootstrap_js:
        inputs:
            - '%kernel.root_dir%/../vendor/twbs/bootstrap/dist/js/bootstrap.js'
#            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-alert.js'
#            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-modal.js'
#            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-dropdown.js'
#            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-scrollspy.js'
#            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-tab.js'
#            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-tooltip.js'
#            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-popover.js'
#            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-button.js'
#            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-collapse.js'
#            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-carousel.js'
#            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-typeahead.js'
#            - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-affix.js'
        filters: [?yui_js]
    bootstrap_less:
        inputs:
            - '%kernel.root_dir%/../vendor/twbs/bootstrap/less/bootstrap.less'
        filters: [lessphp,cssembed]
    saved_search_settings_js:
        inputs:
            - '%kernel.root_dir%/../src/RedEye/SavedSettingsBundle/Resources/public/js/SavedSettingsBundle.js'
        filters: [?yui_js]